language: ruby
cache: bundler
before_install:
    - gem update --system
    - gem install bundler
deploy:
  provider: pages
  local_dir: _site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: docs
